name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "react/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION || '20' }}

      # 👇 Write your multi-line secret directly to .env.production
      - name: Create .env.production
        working-directory: react
        run: |
          : > .env.production
          printf "%s\n" "${{ secrets.FRONTEND_ENV }}" > .env.production
          echo "Wrote react/.env.production"

      - name: Install & Build
        working-directory: react
        env:
          CI: "false"                 # 👈 prevent warnings from failing the build
          # Alternatively (even stricter bypass):
          # DISABLE_ESLINT_PLUGIN: "true"
        run: |
          npm ci
          npm run build

      - name: Tar build
        working-directory: react
        run: tar -czf build.tar.gz build

      - name: Ensure release dir on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            mkdir -p /srv/hrms/frontend/releases/${{ github.sha }}

      - name: Upload artifact to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "react/build.tar.gz"
          target: "/srv/hrms/frontend/releases/${{ github.sha }}/"

      - name: Unpack & switch symlink
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            cd /srv/hrms/frontend/releases/${{ github.sha }}
            tar -xzf build.tar.gz
            rm -f build.tar.gz
            ln -sfn /srv/hrms/frontend/releases/${{ github.sha }}/build /srv/hrms/frontend/current
            cd /srv/hrms/frontend/releases
            ls -1t | tail -n +6 | xargs -r rm -rf
            sudo nginx -t && sudo systemctl reload nginx || true
