name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "react/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        working-directory: react
        env:
          # Inject production envs for the build
          ${{ fromJSON(format('{{"{}"}}', secrets.FRONTEND_ENV)) }}: ''
        run: |
          # Write env file for CRA-style apps (if your app reads from process.env at build)
          echo "${{ secrets.FRONTEND_ENV }}" > .env.production
          npm ci
          npm run build

      - name: Tar build
        working-directory: react
        run: tar -czf build.tar.gz build

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "react/build.tar.gz"
          target: "/srv/hrms/frontend/releases/${{ github.sha }}/"

      - name: Unpack & switch symlink
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /srv/hrms/frontend/releases/${{ github.sha }}
            tar -xzf build.tar.gz
            rm -f build.tar.gz
            # atomically switch current -> this release
            ln -sfn /srv/hrms/frontend/releases/${{ github.sha }}/build /srv/hrms/frontend/current
            # cleanup old releases (keep last 3)
            cd /srv/hrms/frontend/releases
            ls -1t | tail -n +4 | xargs -r rm -rf
            sudo systemctl reload nginx || true
