name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "react/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION || '20' }}

      - name: Install & Build
        working-directory: react
        run: |
          # write production env for build (CRA or Vite — your code must use matching prefixes)
          cat > .env.production << 'EOF'
${{ secrets.FRONTEND_ENV }}
EOF
          npm ci
          npm run build

      - name: Tar build
        working-directory: react
        run: tar -czf build.tar.gz build

      - name: Prepare release dir on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            mkdir -p /srv/hrms/frontend/releases/${{ github.sha }}

      - name: Upload build artifact
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "react/build.tar.gz"
          target: "/srv/hrms/frontend/releases/${{ github.sha }}/"

      - name: Unpack & switch symlink
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /srv/hrms/frontend/releases/${{ github.sha }}
            tar -xzf build.tar.gz && rm -f build.tar.gz
            ln -sfn /srv/hrms/frontend/releases/${{ github.sha }}/build /srv/hrms/frontend/current
            # keep last 3 releases
            cd /srv/hrms/frontend/releases
            ls -1t | tail -n +4 | xargs -r rm -rf
