name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "react/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION || '20' }}

      - name: Create .env.production
        working-directory: react
        run: |
          printf "%s\n" "${{ secrets.FRONTEND_ENV }}" > .env.production

      - name: Install & Build
        working-directory: react
        env:
          CI: "false"                   # keep build from failing on warnings
        run: |
          npm ci
          npm run build

      - name: Ensure release dir on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            mkdir -p /srv/hrms/frontend/releases/${{ github.sha }}/build

      # --- Upload build folder via rsync (no tar files involved) ---
      - name: Upload build with rsync
        uses: burnett01/rsync-deploy@v7
        with:
          switches: -avz --delete
          path: ./react/build/
          remote_path: /srv/hrms/frontend/releases/${{ github.sha }}/build/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Switch symlink & reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            rel="/srv/hrms/frontend/releases/${{ github.sha }}"
            test -d "$rel/build" || (echo "build dir missing in $rel" && exit 1)
            ln -sfn "$rel/build" /srv/hrms/frontend/current
            cd /srv/hrms/frontend/releases
            ls -1t | tail -n +6 | xargs -r rm -rf
            sudo nginx -t && sudo systemctl reload nginx || true
