name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "react/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION || '20' }}

      - name: Create .env.production
        working-directory: react
        run: printf "%s\n" "${{ secrets.FRONTEND_ENV }}" > .env.production

      - name: Install & Build
        working-directory: react
        env:
          CI: "false"
        run: |
          npm ci
          npm run build

      - name: Show build artifact size
        working-directory: react
        run: |
          set -euxo pipefail
          [ -f build.tar.gz ] || tar -czf build.tar.gz build
          du -sh build build.tar.gz

      - name: Ensure release dir on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            mkdir -p /srv/hrms/frontend/releases/${{ github.sha }}

      - name: Upload artifact to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "./react/build.tar.gz"
          target: "/srv/hrms/frontend/releases/${{ github.sha }}/"  # directory
          strip_components: 1                                       # strip 'react/'
          overwrite: true
          timeout: 1200s
          command_timeout: 1200s

      - name: Unpack & switch symlink
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            rel="/srv/hrms/frontend/releases/${{ github.sha }}"
            cd "$rel"

            if [ ! -f build.tar.gz ]; then
              echo "ERROR: build.tar.gz not found in $rel"; ls -laR "$rel"; exit 1
            fi

            tar -xzf build.tar.gz
            rm -f build.tar.gz

            ln -sfn "$rel/build" /srv/hrms/frontend/current
            cd /srv/hrms/frontend/releases
            ls -1t | tail -n +6 | xargs -r rm -rf
            sudo nginx -t && sudo systemctl reload nginx || true
